basePath: /
definitions:
  main.User:
    properties:
      id:
        type: integer
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A secure wallet API with deposits, withdrawals, transfers, and transaction
    history
  title: Wallet & Expense Tracker API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Validates credentials and returns a signed JWT valid for 24 hours
      parameters:
      - description: username and password
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Log in and receive a JWT
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Creates a new user and automatically provisions a wallet with a
        0 balance
      parameters:
      - description: username and password
        in: body
        name: input
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new user account
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
